name: knight
favicon: null
layout_spectrum: 0.9611995965242386
typography_spectrum: 0.6459184128325433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.923320664325729
  lightness: 0.44484857679344714
  saturation: 0.7097945583518595
  rhythmicContrast: 0.6918162901420146
purpose: []
